# Generated by Django 4.1 on 2023-08-28 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seanses', '0004_alter_ticket_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='barcode',
            field=models.ImageField(upload_to='barcodes/', verbose_name='Баркод'),
        ),
    ]
